_target_: hannah.models.capsule_net.SearchSpace
name: capsule_net
params:
  min_reduction: 4
  max_layer: 18 # Number of Conv/OPs
  num_blocks:
    min: 3
    max: 10

  block:
    depth:
      min: 1
      max: 3
    patterns:
      choices: ["convolution", "expand_reduce", "reduce_expand", "pooling"]
      out_channels:
        min: 8
        max: 1024
        step: 4
      stride:
        choices: [1, 2]
      convolution:
        kernel_size:
          choices: [3, 5, 7, 9]
      expand_reduce:
        ratio:
          min: 1.5
          max: 6
      reduce_expand:
        ratio:
          min: 1.5
          max: 6
      pooling:
        kernel_size:
          choices: [3, 5, 7, 9]
        stride:
          choices: [2]
        type:
          choices: ['max', 'avg']
      activation:
        choices: ["relu"]
    residual:
      activation:
        choices: ["relu"]

  stem:
    convolution:
      kernel_size:
        choices: [3,5,7,9]
      stride:
        choices: [1,2]
      out_channels:
        min: 8
        max: 32
        step: 4
    activation:
      choices: ['relu']
  head: []

labels: 10

