# @package _group_

# Nas results:
#   val_error: 0.06459599733352661
#   power_uw: 2.7861697242127517
#   acc_latency: 0.016928

# Backend parameters:
#   backend.cols=8
#   backend.rows=None


_target_: hannah.models.factory.factory.create_cnn
name: dsd22_kws_lp
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 32
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  stride: 2
  target: residual
- blocks:
  - act: false
    kernel_size: 7
    norm: true
    out_channels: 64
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 6
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
