# @package _group_

# Nas results:
#   val_error: 0.03193771839141846
#   power_uw: 0.936509595824098
#   acc_latency: 0.010712

# Backend parameters:
#   backend.cols=4
#   backend.rows=None


_target_: hannah.models.factory.factory.create_cnn
name: dsd22_wwd_ha
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: false
    kernel_size: 7
    norm: true
    out_channels: 4
    parallel: false
    stride: 1
    target: conv1d
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 32
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  stride: 16
  target: forward
- blocks:
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 32
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 5
    norm: true
    out_channels: 52
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 36
    parallel: false
    stride: 1
    target: conv1d
  stride: 16
  target: residual
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 4
    bw_w: 4
    noise_prob: 0.7
    power_of_2: false
