# @package _group_

# Nas results:
#   val_error: 0.05266714096069336
#   power_uw: 4.297028547293796
#   acc_latency: 0.03344

# Backend parameters:
#   backend.cols=8
#   backend.rows=None


_target_: hannah.models.factory.factory.create_cnn
name: dsd22_kws_ha
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 40
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 56
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 1
    norm: true
    out_channels: 24
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 11
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  stride: 2
  target: forward
- blocks:
  - act: false
    kernel_size: 9
    norm: true
    out_channels: 60
    parallel: false
    stride: 1
    target: conv1d
  stride: 2
  target: forward
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 6
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
