_target_: hannah.models.embedded_vision_net.models.embedded_vision_net_large
name: embedded_vision_net_large
num_classes: 10
max_channels: 1024

constraints:
  - name: weights
    # upper: 500000
    # lower: 250000
  - name: macs
    # upper: 128000000
    # lower: 60000000

