  _target_: hannah.models.convnet.ConvNet
  name: lazy_cnn_sequential
  params:
    depth:
      min: 3
      max: 5
    conv:
      kernel_size:
        choices: [3, 5, 7]
      stride:
        choices: [1, 2]
      out_channels:
        min: 16
        max: 64
        step: 4

  labels: 10