

# Backend parameters:
#   backend.cols=4
#   backend.rows=None

# Expected results:#   acc_accuracy: 0.0
#   acc_area: 78466.068
#   acc_clock_cycles: 21148.0
#   acc_power: 4.623608088775999e-06
#   val_error: 0.06212019920349121

_target_: hannah.models.factory.factory.create_cnn
name: nas2_kws_5uw_la_top2
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 20
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 56
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
- blocks:
  - act: true
    kernel_size: 1
    norm: true
    out_channels: 36
    parallel: false
    stride: 1
    target: conv1d
  stride: 1
  target: forward
- blocks:
  - act: false
    kernel_size: 11
    norm: true
    out_channels: 20
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 7
    norm: true
    out_channels: 48
    parallel: false
    stride: 1
    target: conv1d
  - act: false
    kernel_size: 5
    norm: true
    out_channels: 40
    parallel: false
    stride: 1
    target: conv1d
  stride: 4
  target: forward
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 6
    bw_w: 6
    noise_prob: 0.7
    power_of_2: false
