_target_: hannah.models.ofa.models.create
name: ofa_kernel
skew_sampling_distribution: false
min_depth: 5
norm_before_act: true
dropout: 0.5
validate_on_extracted: false
# to add elastic channel count following a module which is not elastic_conv1d
# an "elastic_channel_helper" module with only a channel_count list may be added after
# the maximum channel count of the elastic helper must match the out_channels of the previous module
conv:
  - target: forward
    stride: 1
    blocks:
      - target: conv1d
        kernel_size: 3
        act: false
        norm: true
        out_channels: 16
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: true
        norm: true
        out_channels:
          - 24
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: false
        norm: false
        out_channels:
          - 24
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: true
        norm: true
        out_channels:
          - 32
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: false
        norm: false
        out_channels:
          - 32
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: true
        norm: true
        out_channels:
          - 48
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: false
        norm: false
        out_channels:
          - 48
  - target: residual1d
    stride: 2
    blocks:
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: true
        norm: true
        out_channels:
          - 64
      - target: elastic_conv1d
        kernel_sizes:
          - 9
          - 7
          - 5
          - 3
        act: false
        norm: false
        out_channels:
          - 64
