##
## Copyright (c) 2022 University of Tübingen.
##
## This file is part of hannah.
## See https://atreus.informatik.uni-tuebingen.de/ties/ai/hannah/hannah for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##



# Backend parameters:
#   backend.cols=6
#   backend.rows=None

# Expected results:#   acc_accuracy: 0.0
#   acc_area: 84698.395
#   acc_clock_cycles: 9077.0
#   acc_power: 3.857774222279e-06
#   val_error: 0.06459599733352661

_target_: hannah.models.factory.factory.create_cnn
name: nas2_kws_5uw_lp
norm:
  target: bn
act:
  target: relu
conv:
- blocks:
  - act: true
    kernel_size: 3
    norm: true
    out_channels: 16
    parallel: false
    stride: 1
    target: conv1d
  - act: true
    kernel_size: 5
    norm: true
    out_channels: 56
    parallel: false
    stride: 1
    target: conv1d
  stride: 8
  target: forward
qconfig:
  _target_: hannah.models.factory.qconfig.get_trax_qat_qconfig
  config:
    bw_b: 0
    bw_f: 8
    bw_w: 4
    noise_prob: 0.7
    power_of_2: false
