_target_: pytorch_lightning.trainer.Trainer
gpus: 1
auto_select_gpus: True
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
max_epochs: 100
default_root_dir: .
fast_dev_run: false
overfit_batches: 0.0
benchmark: False
deterministic: True
gradient_clip_val: 0
auto_scale_batch_size: null
accumulate_grad_batches: 1
plugins: null
reload_dataloaders_every_n_epochs: 0
