defaults:
    - config
    - override dataset: siren
    - override model: tc-res8
    - override scheduler: 1cycle
    - override optimizer: adamw
    - override features: mfcc
    - override normalizer: null
    - _self_
