defaults:
    - config
    - override dataset: kvasir_capsule2   # Dataset configuartion name
    - override features: identity        # Feature extractor configuration name (use identity for vision datasets)
    - override model: timm_mobilenetv3_small_100      # Neural network name (for now timm_resnet50 or timm_efficientnet_lite1)
    - override scheduler: 1cycle         # learning rate scheduler config name
    - override optimizer: adamw          # Optimizer config name
    - override normalizer: null          # Feature normalizer (used for quantized neural networks)
    - override module: image_classifier  # Lightning module config for the training loop (image classifier for image classification tasks)
    - override hydra/sweeper: hannah
    - _self_

experiment_id: test
monitor:
  metric: val_f1_micro
  direction: maximize
