##
## Copyright (c) 2022 University of Tübingen.
##
## This file is part of hannah.
## See https://atreus.informatik.uni-tuebingen.de/ties/ai/hannah/hannah for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
defaults:
    - base_config
    - override dataset: cifar10          # Dataset configuration name
    - override features: identity        # Feature extractor configuration name (use identity for vision datasets)
    - override model: resnet             # Neural network name
    - override scheduler: 1cycle         # learning rate scheduler config name
    - override optimizer: adamw          # Optimizer config name
    - override normalizer: null          # Feature normalizer (used for quantized neural networks)
    - override module: image_classifier  # Lightning module config for the training loop (image classifier for image classification tasks)
    - override nas: aging_evolution_nas
    - _self_


# dataset:
#   data_folder: ${oc.env:HANNAH_DATA_FOLDER,${hydra:runtime.cwd}/../../datasets/}

experiment_id: "resnet_nas"

seed: [1234]

model:
  num_classes: 10

nas:
  budget: 500
  n_jobs: 4
  total_candidates: 100
  num_selected_candidates: 10
  sampler:
    population_size: 50
    sample_size: 10

module:
  batch_size: 64
  num_workers: 4

trainer:
  max_epochs: 10

scheduler:
  max_lr: 0.001

fx_mac_summary: True
