defaults:
    - dataset: kvasir_unlabeled           # Dataset configuration name
    - model: timm_mobilenetv3_small_075   # Neural network name (for now timm_resnet50 or timm_efficientnet_lite1)
    - scheduler: 1cycle                   # learning rate scheduler config name
    - optimizer: adamw                    # Optimizer config name
    - normalizer: null                    # Feature normalizer (used for quantized neural networks)
    - module: image_classifier            # Lightning module config for the training loop (image classifier for image classification tasks)
    - trainer: default                    # Lightning trainer config
    - compress: null
    - checkpoint: default
    - backend: null
    - early_stopping: null
    - profiler: null
    - pruning: null
    - augmentation: null
    - override hydra/job_logging: silent

experiment_id: kvasir_ae
output_dir: trained_models
auto_lr: false
print_metrics: false
data_monitor: false
monitor: val_loss
seed: [1234]

checkpoint:
  monitor: val_loss

hydra:
    run:
      dir: ${output_dir}/${experiment_id}/${model.name}/
    sweep:
      dir: ${output_dir}/${experiment_id}/${model.name}/${hydra.job.name}



#TODO:
dump_test: false
input_file: ''
