defaults:
    - config
    - override dataset: pamap2
    - override features: raw
    - override model: tc-res8
    - override scheduler: 1cycle
    - override optimizer: sgd
    - override normalizer: null
    - override module: cross_validation_stream_classifier
    - override trainer: cross_validation
    - override checkpoint: default
    - _self_

experiment_id: test
