defaults:
    - dataset: kws
    - features: mfcc
    - model: conv-net-trax
    - scheduler: 1cycle
    - optimizer: sgd
    - normalizer: fixedpoint
    - module: stream_classifier
    - compress: null
    - trainer: default
    - checkpoint: default
    - backend: trax_ut
    - early_stopping: null
    - profiler: null
    - pruning: null
    - nas: random_nas
    - dataset/features: ${defaults.0.dataset}_${defaults.1.features}
      optional: true

experiment_id: nas_kws2
output_dir: trained_models
auto_lr: false
print_metrics: false
data_monitor: false

seed: [1234]

trainer:
  max_epochs: 30

nas:
  budget: 10
  parametrization:
    _target_: hannah.nas.space.utils.get_example_space

  bounds:
    val_error: 0.06
    # acc_clock_cycles: 25000
    # acc_power: 0.00001
    # acc_area: 200000



hydra:
    run:
      dir: ${output_dir}/${experiment_id}/${model.name}/
    sweep:
      dir: ${output_dir}/${experiment_id}/${model.name}/



#TODO:
dump_test: false
input_file: ''
