
defaults:
    - base_config
    - override dataset: mnist   # Dataset configuration name
    - override features: identity        # Feature extractor configuration name (use identity for vision datasets)
    # - override model: timm_mobilenetv3_small_075      # Neural network name (for now timm_resnet50 or timm_efficientnet_lite1)
    - override scheduler: 1cycle         # learning rate scheduler config name
    - override optimizer: adamw          # Optimizer config name
    - override normalizer: null          # Feature normalizer (used for quantized neural networks)
    - override module: image_classifier  # Lightning module config for the training loop (image classifier for image classification tasks)
    - _self_


dataset:
  data_folder: ${oc.env:HANNAH_DATA_FOLDER,${hydra:runtime.cwd}/../../datasets/}

module:
  batch_size: 128
  num_workers: 0

nas:
  budget: 5
  total_candidates: 5
  num_selected_candidates: 10

trainer:
  max_epochs: 2
  #devices: null
  #accelerator: cpu
  enable_progress_bar: False
  limit_train_batches: 0.1

scheduler:
  max_lr: 0.001

fx_mac_summary: True
