_target_: hannah.nas.OFANasTrainer
epochs_warmup: 35
epochs_kernel_step: 35
epochs_depth_step: 35
epochs_width_step: 35
epochs_dilation_step: 35
elastic_kernels_allowed: True
elastic_depth_allowed: True
elastic_dilation_allowed: True
elastic_width_allowed: True
evaluate: True
random_evaluate: True
random_eval_number: 100
package_eval_models: True
