_target_: hannah.nas.OFANasTrainer
epochs_warmup: 65
epochs_kernel_step: 65
epochs_depth_step: 65
epochs_width_step: 65
epochs_dilation_step: 65
epochs_grouping_step: 65
epochs_dsc_step: 65
elastic_kernels_allowed: True
elastic_depth_allowed: True
elastic_dilation_allowed: False
# with width enabled, the epochs must be 65 for good results
elastic_width_allowed: True
elastic_grouping_allowed: True
#depthwise_separable_convolution
elastic_dsc_allowed: True
evaluate: True
random_evaluate: True
random_eval_number: 100
