_target_: hannah.nas.OFANasTrainer
#epochs_warmup: 35
#epochs_kernel_step: 35
#epochs_depth_step: 35
#epochs_width_step: 35
#epochs_dilation_step: 35
epochs_warmup: 1
epochs_kernel_step: 1
epochs_depth_step: 1
epochs_width_step: 1
epochs_dilation_step: 1
epochs_grouping_step: 1
elastic_kernels_allowed: True
elastic_depth_allowed: True
elastic_dilation_allowed: False
elastic_width_allowed: True
elastic_grouping_allowed: False
evaluate: True
random_evaluate: True
random_eval_number: 1
